### ISSUE TITLE
Error meta is null on Gnome 3.38

### ISSUE THREAD

**Issue by MonsieurV** [UshakovVasilii/gnome-shell-extension-freon#186]
The extension does not work anymore on Gnome 3.38, with the error `TypeError: meta is null`.

Stack trace:

```
(gnome-shell:9657): Gjs-WARNING **: 13:14:26.483: JS ERROR: Extension freon@UshakovVasilii_Github.yahoo.com: TypeError: meta is null
_patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13
_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18
_appendStaticMenuItems@/home/yoan/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:481:20
_updateDisplay@/home/yoan/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:472:18
_updateUI@/home/yoan/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:292:18
_init@/home/yoan/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:119:14
enable@/home/yoan/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:637:17
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:222:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

**Comment by jonasmalacofilho** [comment]
I'm not on 3.38 yet, but this problem is probably fixed by #183 (already merged into the master branch).

**Comment by MonsieurV** [comment]
Indeed this work by manual installation from the master branch.

Could there be a release on https://extensions.gnome.org/extension/841/freon/?

**Comment by UshakovVasilii** [comment]
Done, under review

**Comment by mokilcde** [comment]
Hi!

I have to add also this patch to get it to work:

```
--- /tmp/freonItem.js	2020-10-03 05:46:53.555147052 +0200
+++ freonItem.js	2020-10-03 05:47:41.939514289 +0200
@@ -1,6 +1,7 @@
 const GObject = imports.gi.GObject;
 const PopupMenu = imports.ui.popupMenu;
 const St = imports.gi.St;
+const Clutter = imports.gi.Clutter;
 
 var FreonItem = GObject.registerClass(class FreonItem extends PopupMenu.PopupBaseMenuItem {
 
@@ -10,9 +11,9 @@ var FreonItem = GObject.registerClass(cl
         this._key = key;
         this._gIcon = gIcon;
 
-        this._labelActor = new St.Label({text: displayName ? displayName : label});
+        this._labelActor = new St.Label({text: displayName ? displayName : label, x_align: Clutter.ActorAlign.CENTER, x_expand: true});
         this.actor.add(new St.Icon({ style_class: 'popup-menu-icon', gicon : gIcon}));
-        this.actor.add(this._labelActor, {x_fill: true, expand: true});
+        this.actor.add_child(this._labelActor);
         this._valueLabel = new St.Label({text: value});
         this.actor.add(this._valueLabel);
     }
```

**Comment by UshakovVasilii** [comment]
Looks like latest update work on gnome-shell 3.38 only. I inactivated latest update and uploaded new version for 3.38 only.

![Screenshot_2020-10-03_13-43-44](https://user-images.githubusercontent.com/3512063/94989577-917f7680-057e-11eb-9b9d-3f8a4bcc3181.png)

**Comment by janosbrodbeck** [comment]
I can confirm what @mokilcde posted. Without his patch the extensioned worked somehow, but I couldn't open the popup-menu when I clicked on the item in the panel.
 
Its working fine now with his patch.

**Comment by uno20001** [comment]
I got the following error:

```
JS ERROR: TypeError: meta is null
_patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13
_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18
_init@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/freonItem.js:15:20
_appendMenuItems@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:528:28
_updateDisplay@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:462:22
_updateUI@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:297:18
_init/this._updateUITimeoutId<@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:122:18

```
and I can confirm that @mokilcde's patch works.

**Comment by jonasmalacofilho** [comment]
Just upgraded to 3.38 myself.  I found that @mokilcde's patch messed up the aligned on the Freon items, so I slightly changed it to:

```diff
diff --git a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
index 05d623da88ed..901e0e4a4608 100644
--- a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
+++ b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
@@ -10,9 +10,9 @@ var FreonItem = GObject.registerClass(class FreonItem extends PopupMenu.PopupBas
         this._key = key;
         this._gIcon = gIcon;
 
-        this._labelActor = new St.Label({text: displayName ? displayName : label});
+        this._labelActor = new St.Label({text: displayName ? displayName : label, x_expand: true});
         this.actor.add(new St.Icon({ style_class: 'popup-menu-icon', gicon : gIcon}));
-        this.actor.add(this._labelActor, {x_fill: true, expand: true});
+        this.actor.add_child(this._labelActor);
         this._valueLabel = new St.Label({text: value});
         this.actor.add(this._valueLabel);
     }
```

<details><summary>Expand for diff on top of @mokilcde's patch.</summary>

```diff
diff --git a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
index 84c4c8989ccf..901e0e4a4608 100644
--- a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
+++ b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
@@ -1,7 +1,6 @@
 const GObject = imports.gi.GObject;
 const PopupMenu = imports.ui.popupMenu;
 const St = imports.gi.St;
-const Clutter = imports.gi.Clutter;
 
 var FreonItem = GObject.registerClass(class FreonItem extends PopupMenu.PopupBaseMenuItem {
 
@@ -11,7 +10,7 @@ var FreonItem = GObject.registerClass(class FreonItem extends PopupMenu.PopupBas
         this._key = key;
         this._gIcon = gIcon;
 
-        this._labelActor = new St.Label({text: displayName ? displayName : label, x_align: Clutter.ActorAlign.CENTER, x_expand: true});
+        this._labelActor = new St.Label({text: displayName ? displayName : label, x_expand: true});
         this.actor.add(new St.Icon({ style_class: 'popup-menu-icon', gicon : gIcon}));
         this.actor.add_child(this._labelActor);
         this._valueLabel = new St.Label({text: value});
```
</details>

**Comment by UshakovVasilii** [comment]
Please create pull request, I cannot check it, I'm using Xfce now

**Comment by mokilcde** [comment]
Done #188

**Comment by gilvbp** [comment]
> Just upgraded to 3.38 myself. I found that @mokilcde's patch changed the alignment on the Freon items, so I slightly changed it to:
> 
> ```diff
> diff --git a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
> index 05d623da88ed..901e0e4a4608 100644
> --- a/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
> +++ b/freon@UshakovVasilii_Github.yahoo.com/freonItem.js
> @@ -10,9 +10,9 @@ var FreonItem = GObject.registerClass(class FreonItem extends PopupMenu.PopupBas
>          this._key = key;
>          this._gIcon = gIcon;
>  
> -        this._labelActor = new St.Label({text: displayName ? displayName : label});
> +        this._labelActor = new St.Label({text: displayName ? displayName : label, x_expand: true});
>          this.actor.add(new St.Icon({ style_class: 'popup-menu-icon', gicon : gIcon}));
> -        this.actor.add(this._labelActor, {x_fill: true, expand: true});
> +        this.actor.add_child(this._labelActor);
>          this._valueLabel = new St.Label({text: value});
>          this.actor.add(this._valueLabel);
>      }
> ```

> 
> Expand for diff on top of @mokilcde's patch.
Nice, now it's working, but still missing item text labels. Only showing temps on the list.

**Comment by jonasmalacofilho** [comment]
@gilvbp that's curious, text labels are showing fine for me (and I imagine for the others that posted here).

Can you post a screenshot and take a look at the logs?

**Comment by gilvbp** [comment]
> @gilvbp that's curious, text labels are showing fine for me (and I imagine for the others that posted here).
> 
> Can you post a screenshot and take a look at the logs?

I double-check the .js and saw that was missing `const Clutter = imports.gi.Clutter;`. Now it's ok. Obrigado, doutor! Tmj

**Comment by jonasmalacofilho** [comment]
@gilvbp great!

Although that's only necessary if you have kept `x_align: Clutter.ActorAlign.CENTER`.

**Comment by spxak1** [comment]
Is a newer version that works in 3.38 available now? How can we get it? Thanks.

**Comment by UshakovVasilii** [comment]
@spxak1 you can use https://extensions.gnome.org/extension/841/freon/

**Comment by spxak1** [comment]
> @spxak1 you can use https://extensions.gnome.org/extension/841/freon/

Thanks, but this is what I get:

`JS ERROR: Extension freon@UshakovVasilii_Github.yahoo.com: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data @ /home/otheos/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/nvmecliUtil.js:7`

**Comment by mokilcde** [comment]
Hi!

The merge request is already pushed so it shall be available.

But you can chekcout the git version and see whether it works

CU
  Michael

> Is a newer version that works in 3.38 available now? How can we get it? Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 
CU  
         
  Michael
          
-- 
    ,''`.   
   : :' :   Michael Ott 
   `. `'    e-mail: michael at k-c13 dot org
     `-

Gem. Par. 28 Abs. 4 Bundesdatenschutzgesetz widerspreche ich der Nutzung
sowie der Weitergabe meiner personenbezogenen Daten für Zwecke der
Werbung sowie der Markt- oder Meinungsforschung.
